### ISSUE TITLE
core.js:6014 ERROR Could not load viewer config

### ISSUE THREAD

**Issue by ShiftD3l** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms#83]
Running the solution locally produces no issues. Running it on IIS produces the following exception in console log:

core.js:6014 ERROR Could not load viewer config: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":404,"statusText":"OK","url":"https://docviewer.cx360.net/viewer/loadConfig","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://docviewer.cx360.net/viewer/loadConfig: 404 OK","error":{"Message":"No HTTP resource was found that matches the request URI 'http://docviewer.cx360.net/viewer/loadConfig'."}}

**Comment by bobkovalex** [comment]
Hi @ShiftD3l 

I apologise for not replying sooner.
We've found and fixed an issue which was preventing application form running on custom IP/domain, so please checkout latest commit from master branch and follow this guide on [how-to use custom domains](https://products.conholdate.app/viewer/view/59mhVoboa6I5O4DL3/using-custom-host-url-step-by-step-guide.docx?preview=true.pdf).

Please note that we are currently working on adding baseURL parameter to the config file so that this process would be much more simple.

Best regards,
Alex
